version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'RabbitMQ'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - "RABBITMQ_DEFAULT_PASS=!Malinka@pass"
      - "RABBITMQ_DEFAULT_USER=libman"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    container_name: 'Identity.api'
    ports:
      - 5001:80
    build:
      context: .
      dockerfile: Identity.API/Dockerfile

  library.api:
    image: ${DOCKER_REGISTRY-}libraryapi
    container_name: 'Library.api'
    ports:
      - 5002:80
    build:
      context: .
      dockerfile: Library.API/Dockerfile
      
  book.api:
    image: ${DOCKER_REGISTRY-}bookapi
    container_name: 'Book.api'
    ports:
      - 5003:80
    build:
      context: .
      dockerfile: Book.API/Dockerfile

